name: Test and Build Python MCP Server

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Updated from 3.9 to 3.10 to meet MCP requirements

    # Install Python dependencies using uv
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip uv
        uv pip install --system -r requirements.txt

    # Run Python tests
    - name: Run Python tests
      run: |
        python test_example.py > test_results.log 2>&1
      continue-on-error: false

    # Upload test logs as artifacts
    - name: Upload test logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: test_results.log
        retention-days: 7

    # Build Docker image
    - name: Build Docker image
      run: |
        # Use the same image name as in docker-test.sh for consistency, though the script rebuilds it.
        docker build -t gatherings-mcp-test .

    # Test Docker image using the script
    - name: Test Docker image
      run: |
        chmod +x ./docker-test.sh
        ./docker-test.sh

    # Upload build artifacts (Removed redundant log files)
    - name: Upload build artifacts
      if: failure() # Optionally upload only on failure, or keep always() if needed
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts # Consider renaming or removing if only test logs are needed
        # No specific build artifacts generated by the script in this version
        # path: |
        #   docker-image-info.json
        #   docker-build-result.log
        #   docker-test-output.log
        retention-days: 5
